services:

  mailpit:
    image: axllent/mailpit:latest
    container_name: integration-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  notification-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker,e2e